problems/paintful-intersections/solutions/Main.class: problems/paintful-intersections/solutions/paintful-intersections.scala
	scalac -d $(<D) -sourcepath $(<D) $<

test-paintful-intersections: problems/paintful-intersections/solutions/Main.class
